services:
  web_server:
    image: autofunbot/tg_web_server
    restart: always
    networks:
      services_net:
        ipv4_address: 10.41.0.2
  mysql_server:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=lab123
      - MYSQL_USER=lab
      - MYSQL_DATABASE=lab_db
      - MYSQL_PASSWORD=lab123
    networks:
      services_net:
        ipv4_address: 10.41.0.3
  ftp_server:
    image: 'delfer/alpine-ftp-server'
    restart: always
    environment:
      - USERS=lab|Juniper123
    networks:
      services_net:
        ipv4_address: 10.41.0.4
  web_client:
    image: autofunbot/tg_web_client
    restart: always
    environment:
      - TARGETS=10.42.0.2 10.43.0.2
  mysql_client:
    image: autofunbot/tg_sql_client
    restart: always
    environment:
      - TARGETS=10.42.0.3 10.43.0.3
  ftp_client:
    image: autofunbot/tg_ftp_client
    restart: always
    environment:
      - TARGETS=10.42.0.4 10.43.0.4
networks:
  services_net:
    name: services_net
    driver: ipvlan
    driver_opts:
      parent: wlan1
    ipam:
      config:
        - subnet: 10.41.0.0/24
          ip_range: 10.41.0.0/24
          gateway: 10.41.0.1