services:
  web:
    image: nginx
    ports:
      - '80:80'
    networks:
      - web_net
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=lab123
      - MYSQL_USER=lab
      - MYSQL_DATABASE=lab_db
      - MYSQL_PASSWORD=lab123
    networks:
      - db_net
  ftp:
    image: 'delfer/alpine-ftp-server'
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS="lab|lab123"
      - ADDRESS=ftp
    networks:
      - ftp_net
networks:
  web_net:
  db_net:
  ftp_net:
