---
- name: Install Docker
  hosts: tg_hosts
  vars:
    - ansible_become_password: juniper123
    - ansible_become_user: root
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
      become: true
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      become: true
    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
      become: true

    - name: Install Docker Module for Python
      pip:
        name: docker
      become: true

- name: Install config files
  hosts: tg_hosts
  vars:
    - ansible_become_password: juniper123
    - ansible_become_user: root

  tasks:
  - name: Create mosquitto dir
    file:
      path: /home/lab/mosquitto
      state: directory
    become: true
  - name: Install MQTT config
    template:
      src: templates/mosquitto.conf.j2
      dest: /home/lab/mosquitto/mosquitto.conf
      owner: root
      mode: '0644'
    become: true